name: Run Engine Script

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours at the start of the hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Restore fetched_articles.json artifact (if available)
    - name: Restore fetched_articles.json artifact (if available)
      uses: actions/download-artifact@v4
      with:
        name: fetched-articles
        path: .
      continue-on-error: true  # Allow workflow to continue even if no artifact is found

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run engine script
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python engine.py

    - name: Upload fetched_articles.json artifact
      uses: actions/upload-artifact@v4
      with:
        name: fetched-articles
        path: fetched_articles.json
        include-hidden-files: true  # Include hidden files if necessary
