name: Run Engine

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:
  run-engine:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run engine.py
      - name: Run engine.py
        run: python engine.py

      # Step 5: Commit and push updated JSON to the repository
      - name: Commit and Push updated fetched_articles.json
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update fetched_articles.json with new article URLs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
